import = [
  "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[shell] 
program = "/opt/homebrew/bin/zellij"

[env]
TERM = "xterm-256color"

[window]
padding.x = 6
padding.y = 3
opacity = 0.7
blur = true
startup_mode = "Maximized"
option_as_alt = "Both"
decorations = "Buttonless"

[font]
size = 12

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" }  
]
